blog/urls.py
from django.urls import path
from blog.views import(

	create_blog_view,
	detail_blog_view,
	edit_blog_view,

)

app_name = 'blog'

urlpatterns = [
	path('create/', create_blog_view, name="create"),
	path('<slug>/', detail_blog_view, name="detail"),
	path('<slug>/edit', edit_blog_view, name="edit"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from personal.views import (
	home_screen_view,
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('account/', account_view, name="account"),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),
	
	# REST-framework
    path('api/blog/', include('blog.api.urls', 'blog_api')),
    path('api/account/', include('account.api.urls', 'account_api')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/base_css.html
<style type="text/css">
    body {
        background-color: whitesmoke;
    }
</style>

templates/snippets/footer.html
<style type="text/css">
    .footer {
        min-height: 50px;
    }
</style>

<!-- Footer -->

<div class="d-flex flex-row align-items-center footer bg-white shadow-lg">
    <p class="m-auto"> <span style="color: blue;">Kemri | 2022</span> </p>
</div>
<!-- End Footer -->


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

templates/snippets/header.html
<style type="text/css">
    @media (min-width: 768px) {
        html {
            font-size: 16px;
        }
    }
    
    .search-bar {
        max-width: 500px;
        width: 100%;
    }
    
    form {
        width: 100%;
    }
</style>

<!-- Header -->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">
        {% if request.user.is_authenticated %}
        <p>
            <span style="color: blue;">Logged in as:</span> {{request.user.username}}, kemri staff</p>
        <a class="btn btn-primary " href="{% url 'blog:create' %} "><span style="color: white;">DASHBOARD</span></a> {% endif %}
    </h5>

    <div class="search-bar mt-sm-2 mr-2">

        <form onsubmit="return executeQuery();">
            <input type="text" class="form-control" name="q" id="id_q" placeholder="Search...">
        </form>
    </div>

    <nav class="my-2 my-md-0 mr-md-3">
        {% if request.user.is_authenticated %}
        <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
        <a class="p-2 text-dark" href="{% url 'account' %}">Account</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Logout</a> {% else %}
        <a class="p-2 text-dark" href="{% url 'home' %}">Home</a>
        <a class="p-2 text-dark" href="{% url 'login' %}">Login</a>
        <a class="btn btn-outline-primary" href="{% url 'register' %}">Add Staff</a> {% endif %}

    </nav>
</div>

<script type="text/javascript">
    document.getElementById("id_q").value = "{{query}}"
</script>
<script type="text/javascript">
    function executeQuery() {
        var query = document.getElementById("id_q").value
        window.location.replace("http://127.0.0.1:8000/?q=" + query)
            // "https://open-api.xyz/?q=" + query
        return false
    }
</script>

<!-- End Header -->